### ISSUE TITLE
应该装在devDependencies

### ISSUE THREAD

**Issue by Kory-lee** [luxueyan/vite-transform-globby-import#2]
装在dependencies会报错...
```sh
[vite] Dep optimization failed with error:
Dependency vite-transform-globby-import is attempting to import Node built-in module fs.
This will not work in a browser environment.
Imported by: node_modules\vite-transform-globby-import\dist\index.js        

Tip:
Make sure your "dependencies" only include packages that you
intend to use in the browser. If it's 
a Node.js package, it
should be in "devDependencies".       

If you do intend to use this dependency in the browser and the
dependency does not actually use these Node built-ins in the
browser, you can add the dependency (not the built-in) to the
"optimizeDeps.allowNodeBuiltins" option in vite.config.js.

If that results in a runtime error, then unfortunately the
package is not distributed in a web-friendly format. You should
open an issue in its repo, or look for a modern alternative.
```

给下一个踩坑的
```sh
yarn add -D vite-transform-globby-import or npm i --dev vite-transform-globby-import
```

**Comment by Kory-lee** [comment]
> 装在dependencies会报错...
> 
> ```shell
> [vite] Dep optimization failed with error:
> Dependency vite-transform-globby-import is attempting to import Node built-in module fs.
> This will not work in a browser environment.
> Imported by: node_modules\vite-transform-globby-import\dist\index.js        
> 
> Tip:
> Make sure your "dependencies" only include packages that you
> intend to use in the browser. If it's 
> a Node.js package, it
> should be in "devDependencies".       
> 
> If you do intend to use this dependency in the browser and the
> dependency does not actually use these Node built-ins in the
> browser, you can add the dependency (not the built-in) to the
> "optimizeDeps.allowNodeBuiltins" option in vite.config.js.
> 
> If that results in a runtime error, then unfortunately the
> package is not distributed in a web-friendly format. You should
> open an issue in its repo, or look for a modern alternative.
> ```
> 
> 给下一个踩坑的
```sh
yarn add -D vite-transform-globby-import or npm i --dev vite-transform-globby-import
```

**Comment by Kory-lee** [comment]
> 装在dependencies会报错...
> 
> ```shell
> [vite] Dep optimization failed with error:
> Dependency vite-transform-globby-import is attempting to import Node built-in module fs.
> This will not work in a browser environment.
> Imported by: node_modules\vite-transform-globby-import\dist\index.js        
> 
> Tip:
> Make sure your "dependencies" only include packages that you
> intend to use in the browser. If it's 
> a Node.js package, it
> should be in "devDependencies".       
> 
> If you do intend to use this dependency in the browser and the
> dependency does not actually use these Node built-ins in the
> browser, you can add the dependency (not the built-in) to the
> "optimizeDeps.allowNodeBuiltins" option in vite.config.js.
> 
> If that results in a runtime error, then unfortunately the
> package is not distributed in a web-friendly format. You should
> open an issue in its repo, or look for a modern alternative.
> ```
> yarn add -D vite-transform-globby-import or npm i --dev vite-transform-globby-import
> 给下一个踩坑的

**Comment by luxueyan** [comment]
It is optimizing behavior of vite about the 'dependencies'. And this is a plugin of development, you should better install it in ’ devDependencies‘
